src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * User
 *
 * @ORM\Table(name="user", uniqueConstraints={@ORM\UniqueConstraint(name="email", columns={"email"})}, indexes={@ORM\Index(name="id_rol", columns={"id_rol"})})
 * @ORM\Entity
 */
class User implements UserInterface{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=255, nullable=false)
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column(name="alias", type="string", length=45, nullable=false)
     */
    private $alias;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255, nullable=false)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="surnames", type="string", length=255, nullable=false)
     */
    private $surnames;

    /**
     * @var string
     *
     * @ORM\Column(name="image", type="string", length=255, nullable=false)
     */
    private $image;

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(name="birth_date", type="date", nullable=true)
     */
    private $birthDate;

    /**
     * @var string|null
     *
     * @ORM\Column(name="direccion", type="string", length=255, nullable=true)
     */
    private $direccion;

    /**
     * @var string|null
     *
     * @ORM\Column(name="phone", type="string", length=45, nullable=true)
     */
    private $phone;

    /**
     * @var string
     *
     * @ORM\Column(name="password", type="string", length=255, nullable=false)
     */
    private $password;

    /**
     * @var bool
     *
     * @ORM\Column(name="active", type="boolean", nullable=false)
     */
    private $active = '0';

    /**
     * @var \Rol
     *
     * @ORM\ManyToOne(targetEntity="Rol")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_rol", referencedColumnName="id")
     * })
     */
    private $Rol;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getAlias(): ?string
    {
        return $this->alias;
    }

    public function setAlias(string $alias): self
    {
        $this->alias = $alias;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSurnames(): ?string
    {
        return $this->surnames;
    }

    public function setSurnames(?string $surnames): self
    {
        $this->surnames = $surnames;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birthDate;
    }

    public function setBirthDate(?\DateTimeInterface $birthDate): self
    {
        $this->birthDate = $birthDate;

        return $this;
    }

    public function getDireccion(): ?string
    {
        return $this->direccion;
    }

    public function setDireccion(?string $direccion): self
    {
        $this->direccion = $direccion;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getPassword(): ?string
    {
        if ($this->getActive()) {
            return $this->password;
        }
        
        return "";
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getRol(): ?Rol
    {
        return $this->Rol;
    }

    public function setRol(?Rol $Rol): self
    {
        $this->Rol = $Rol;

        return $this;
    }


    public function getUserName(){
        return $this->email;
    }

    public function getSalt(){
        return null;
    }

    public function getRoles(){

        $roles = array($this->getRol()->getName());
        return $roles;
    }

    public function eraseCredentials(){

    }

    public function isEnabled(){
        return $this->getActive();
    }

}

templates/_includes/admin-top-bar.html.twig
<!-- Menú de administración -->

<!--Navbar -->
<nav id="admin-menu" class="mb-0 navbar navbar-expand-lg navbar-dark  ">
	<a class="navbar-brand" href="#">ADMIN</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-555"
	aria-controls="navbarSupportedContent-555" aria-expanded="false" aria-label="Toggle navigation">
	<span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarSupportedContent-555">
	<ul class="navbar-nav mr-auto">

		<li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" data-toggle="dropdown"
			aria-haspopup="true" aria-expanded="false">Negocios
		</a>
		<div class="dropdown-menu dropdown-secondary" aria-labelledby="navbarDropdownMenuLink-555">
			<a class="nav-link" href="{{path('admin-businesses')}}"><i class="fas fa-cogs"></i> Administrar</a>
			<a class="dropdown-item" href="{{path('create-business')}}"><i class="fas fa-plus-square"></i> Nuevo</a>
		</div>
	</li>

	<li class="nav-item dropdown">
		<a class="nav-link dropdown-toggle" data-toggle="dropdown"
		aria-haspopup="true" aria-expanded="false">Eventos
	</a>
	<div class="dropdown-menu dropdown-secondary" aria-labelledby="navbarDropdownMenuLink-555">
		<a class="nav-link" href="{{path('admin-events')}}"><i class="fas fa-cogs"></i> Administrar</a>
		<a class="dropdown-item" href="{{path('create-event')}}"><i class="fas fa-plus-square"></i> Nuevo</a>
	</div>
</li>
<li class="nav-item dropdown">
	<a class="nav-link dropdown-toggle" data-toggle="dropdown"
	aria-haspopup="true" aria-expanded="false">Usuarios
</a>
<div class="dropdown-menu dropdown-secondary" aria-labelledby="navbarDropdownMenuLink-555">
	<a class="nav-link" href="{{path('admin-users')}}"><i class="fas fa-cogs"></i> Administrar</a>
	<a class="dropdown-item" href="{{path('create-user')}}"><i class="fas fa-plus-square"></i> Nuevo</a>
</div>
</li>
<li class="nav-item dropdown">
	<a class="nav-link dropdown-toggle" data-toggle="dropdown"
	aria-haspopup="true" aria-expanded="false">Blog</a>
	<div class="dropdown-menu dropdown-secondary" aria-labelledby="navbarDropdownMenuLink-555">
		<a class="nav-link" href="{{path('admin-blogs')}}"><i class="fas fa-cogs"></i> Administrar</a>
		<a class="dropdown-item" href="{{path('create-blog')}}"><i class="fas fa-plus-square"></i> Nuevo</a>
	</div>
</li>
</ul>
<ul class="navbar-nav ml-auto nav-flex-icons">
	<li class="nav-item avatar ">
		<a style="background-image: url({{asset('assets/img/user/')}}{{app.user.image}})" class="nav-link rounded-circle z-depth-0 avatar" id="navbarDropdownMenuLink-55" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

		</a>
</li>
</ul>
</div>

<!--/.Navbar -->
</nav>
<!-- Fin Menú de administración -->

templates/_includes/footer.html.twig
{# Footer #}
<footer class="container-fluid footer">

  <div class="row inner_footer align-items-center">
    <div class="col-12 col-md-3 logo_container text-center">
      <img src="{{asset('assets/img/logo.png')}}" alt="">
    </div>


    <div class="col-12 col-md-9 inner_footer ">
      <div class="row">
        <div class="col-12 col-md-3 footer_third text-center text-md-left">
          <h4>¿Necesitas ayuda?</h4>
          <ul class="list-unstyled">
            <li><a href="#">Terminos &amp; Condiciones</a></li>
            <li><a href="#">Politica de privacidad</a></li>
          </ul>
        </div>

        <div class="col-12 col-md-3 footer_third align-items-center text-center text-md-left ">
          <h4>Más información</h4>
          <ul class="list-unstyled">
            <li><a href="#">Publicidad</a></li>
            <li><a href="#">Trabaja con nosotros</a></li>
            <li><a href="#">Donaciones</a></li>
            <li><a href="#">Colabora</a></li>
            <li><a href="#">Reportes</a></li>
          </lu>
        </div>

        <div class="col-12 col-md-3 footer_third text-center text-md-left">
          <h4>Sobre nosotros</h4>
          <ul class="list-unstyled">
            <li>Marta Jimenez Martinez</li>
            <li>Francisco Javier Montoro López</li>
            <li>Francisco Jesús Moreno Rodríguez</li>
            <li>Miguel Ángel Pérez Morales</li>
            <li>Daniel Villodres López</li>
          </ul>
        </div>

        <div class="col-12 col-md-3 footer_third text-center text-md-left">
          <h4>Redes Sociales</h4>
          <ul class="list-unstyled d-flex icons justify-content-around offset-2 col-8 pt-2 offset-md-0 col-md-7 pl-md-0">
            <li><a href=""><i class="fab fa-facebook-square"></i></a></li>
            <li><a href=""><i class="fab fa-twitter-square"></i></a></li>
            <li><a href=""><i class="fab fa-github-square"></i></a></li>
            <li><a href=""><i class="fab fa-instagram"></i></a></li>
          </ul>
        </div>

      </div>
    </div>
  </div>
</footer>
{% include '_includes/forgotpasswordmodal.html.twig' %}

templates/_includes/forgotpasswordmodal.html.twig
<div class="modal fade forget-modal" id="" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h4 class="modal-title w-100 font-weight-bold">Recuperar Contraseña</h4>
      </div>
      <div class="modal-body mx-3">
        <div class="d-flex justify-content-center">
          <div id="passwordLoading" style="display:none" class="spinner-grow " role="status">
            <span class="sr-only">Loading...</span>
          </div>
        </div>
  
        <div id="passwordChanged" style="display:none" class="alert alert-success fadeIn animated ">
          <small>Tu contraseña se ha modificado y se te ha enviado a tu email.</small>
        </div>
        <div id="userNotExist" style="display:none" class="alert alert-danger fadeIn animated ">
          <small>El email no corresponde a ningún usuario.</small>
        </div>        <div class="md-form mb-5">
          <input type="email" id="email" class="form-control">
          <label for="email">Correo Electrónico</label>
        </div>
		<small>Te enviaremos un email con una nueva contraseña, después es recomendable que la cambies.</small>
      </div>
      <div class="modal-footer d-flex justify-content-center">
        <button id="recoverPassword" class="btn btn-orange">Envíar contraseña</button>
        <button id="" class="btn btn-orange"  data-dismiss="modal" aria-label="Close">Cerrar</button>
      </div>
    </div>
  </div>
</div>


<script>

  $('#recoverPassword').click(function(){

    $('#passwordLoading').show();
    $('#userNotExist').hide();
    $('#passwordChanged').hide();

  var form = new FormData();
  form.append("email", $('#email').val());

  var settings = {
    "url": "{{path('recover-password')}}",
    "method": "POST",
    "timeout": 0,
    "processData": false,
    "mimeType": "multipart/form-data",
    "contentType": false,
    "data": form
  };

  $.ajax(settings).done(function (response) {
      var data = $.parseJSON(response);
      if (data.status == true) {
        $('#passwordLoading').hide();
        $('#passwordChanged').show();


      }else{
        $('#passwordLoading').hide();
        $('#userNotExist').show();

      }
  });
  });

</script>

templates/_includes/head.html.twig
{# Head #}

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">


<!-- Importamos las librerías necesarias para el uso de bootstrap, tenemos la documentación disponible en https://getbootstrap.com/docs/4.4 -->

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>

<!-- Material Design Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.0/css/mdb.min.css" rel="stylesheet">

<!-- Importamos las tipografías desde google fonts -->
<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600&family=Roboto:wght@400;500;600;700&display=swap" rel="stylesheet">


<!-- JQuery -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<!-- Fonts Awesome -->
<script defer src="https://use.fontawesome.com/releases/v5.0.13/js/all.js" integrity="sha384-xymdQtn1n3lH2wcu0qhcdaOpQwyoarkgLVxC/wZ5q7h9gHtxICrpcaSUfygqZGOe" crossorigin="anonymous"></script>

<!-- Mobile Detect -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/UAParser.js/0.7.19/ua-parser.min.js"></script>


<!-- Importamos nuestros estilos css propios -->

<link rel="stylesheet" href="{{asset('assets/css/style.css')}}">

<script src="{{asset('assets/js/helpers.js')}}"></script>

<!-------------------------------------------------------------------------->
<!--                             FAVICON                                  -->
<!-------------------------------------------------------------------------->

<link rel="apple-touch-icon" sizes="57x57" href="{{asset('assets/img/favicon' ~ '/apple-icon-57x57.png')}}">
<link rel="apple-touch-icon" sizes="60x60" href="{{asset('assets/img/favicon' ~ '/apple-icon-60x60.png')}}">
<link rel="apple-touch-icon" sizes="72x72" href="{{asset('assets/img/favicon' ~ '/apple-icon-72x72.png')}}">
<link rel="apple-touch-icon" sizes="76x76" href="{{asset('assets/img/favicon' ~ '/apple-icon-76x76.png')}}">
<link rel="apple-touch-icon" sizes="114x114" href="{{asset('assets/img/favicon' ~ '/apple-icon-114x114.png')}}">
<link rel="apple-touch-icon" sizes="120x120" href="{{asset('assets/img/favicon' ~ '/apple-icon-120x120.png')}}">
<link rel="apple-touch-icon" sizes="144x144" href="{{asset('assets/img/favicon' ~ '/apple-icon-144x144.png')}}">
<link rel="apple-touch-icon" sizes="152x152" href="{{asset('assets/img/favicon' ~ '/apple-icon-152x152.png')}}">
<link rel="apple-touch-icon" sizes="180x180" href="{{asset('assets/img/favicon' ~ '/apple-icon-180x180.png')}}">
<link rel="icon" type="image/png" sizes="192x192"  href="{{asset('assets/img/favicon' ~ '/android-icon-192x192.png')}}">
<link rel="icon" type="image/png" sizes="32x32" href="{{asset('assets/img/favicon' ~ '/favicon-32x32.png')}}">
<link rel="icon" type="image/png" sizes="96x96" href="{{asset('assets/img/favicon' ~ '/favicon-96x96.png')}}">
<link rel="icon" type="image/png" sizes="16x16" href="{{asset('assets/img/favicon' ~ '/favicon-16x16.png')}}">
<link rel="manifest" href="{{asset('assets/img/favicon' ~ '/manifest.json')}}">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="{{asset('assets/img/favicon' ~ '/ms-icon-144x144.png')}}">
<meta name="theme-color" content="#ffffff">

<!-------------------------------------------------------------------------->
<!--                             FAVICON                                  -->
<!-------------------------------------------------------------------------->

templates/_includes/header.html.twig
{# Header #}
{# Con este if controlamos si el usuario es administrador, en caso de serlo se muestra la barra de administrador #}
{% if app.user %}
	{% if app.user.rol.name == "ROLE_ADMIN" %}
{# Incluimos el documento con la información de la barra de administrador #}
		{% include '_includes/admin-top-bar.html.twig' %}
	{% endif %}
{% endif %}
<header class="">

{# Barra de menus para móvil #}
	<div id="mobile-menu-button" class="menu_bar">
		<p class="title">Un Color Especial</p>
		<i class=" menu-button fas fa-bars"></i>
	</div>

{# Barra de menú normal #}
	<nav id="main-menu" class="">
		<div class="menu-box">
			<ul>
				<li><a href='{{path('home')}}'>Inicio</a></li>
				<li><a href='{{path('categories')}}'>Blog</a></li>
				<li><a href='{{path('business-categories')}}'>Negocios</a></li>
			</ul>

			<img id='logo' src='{{asset('assets/img/')}}logo.png'>

			<ul>
				<li><a href='{{path('event-categories')}}'>Eventos</a></li>
				<li><a href='{{path('contact-form')}}'>Contacto</a></li>


				{% if app.user %}
				<li>
					<div class="dropdown show">
					<a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Perfil</a>
						<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
						    <a class="dropdown-item" href="{{path('edit-user')}}"><i class="fas fa-user-edit"></i> Editar Perfil</a>
						    <div class="dropdown-divider"></div>
						    <a class="dropdown-item" href="{{path('logout')}}"><i class="fas fa-sign-out-alt"></i> Cerrar Sesion</a>
						</div>
					</div>
				</li>
				{% else %}
				<li><a href='{{path('login')}}'>Iniciar sesión</a></li>
				{% endif %}

			</ul>
		</div>
	</nav>
</header>
<!-- Fin Header -->

templates/_includes/instagramFeed.html.twig
{# Instagram feed pagina principal #}
<section class="container">

{# Incluimos el script necesario para obtener la información de instagram #}
<script src="{{asset('assets/js/jquery.instagramFeed.js')}}"></script>

{# Creamos el div donde se muestra la información y el script necesario #}

<div id="instagramFeed" class="instagram_feed "></div>

<script>
(function($){
  $(window).on('load', function(){
    $.instagramFeed({
      'username': 'uncolorespecialfct',
      'container': "#instagramFeed",
      'display_profile': true,
      'display_gallery': true,
      'items': 10,
      'items_per_row': 5,
      'margin': 0.5
    });
  });
})(jQuery);
</script>

</section>

templates/_includes/instagramFeedBusiness.html.twig
{# Instagram feed pagina negocios #}
<script src="{{asset('assets/js/jquery.instagramFeed.js')}}"></script>

{# Incluimos el script necesario para obtener la información de instagram #}
<div id="instagramFeed" class="instagram_feed my-5"></div>

{# Creamos el div donde se muestra la información y el script necesario #}
<script>
(function($){
  $(window).on('load', function(){
    $.instagramFeed({
      'username': '{{business.instagram}}',
      'container': "#instagramFeed",
      'display_profile': true,
      'display_gallery': true,
      'items': 10,
      'items_per_row': 5,
      'margin': 0.5
    });
  });
})(jQuery);
</script>

templates/_includes/modal.html.twig
{# Modal #}
<div id="myModal" class="modal myModal">
	<span class="close">&times;</span>
	<img class="modal-content" id="img01">
	<div id="caption"></div>
</div>

templates/_includes/registeredUser.html.twig
{# Controlamos si el usuario esta registrado y mostramos un mensaje acorde #}
{% if app.user %}

{% set content = 'Bienvenido de nuevo ' ~ app.user.name ~ ' ' ~ app.user.surnames %}
{# incluimos el bloque de contenido 7 #}
{% include '_includes/blocks/block7.html.twig'%}
<div class="menu-box">
	<ul>
		<li><a href='{{path('edit-user')}}'>Edita tus datos</a></li>
	</ul>
</div>

{# En caso de no estar registrado se muestran opciones para hacer login o registrarse #}
{% else %}

{% set content = 'Inicie sesión o regístrese en los siguientes enlaces' %}
{# Inclimos el bloque de contenido 7 #}
{% include '_includes/blocks/block7.html.twig'%}
<div class="menu-box">
	<ul>
		<li><a href='{{path('register-user')}}'>Crea una cuenta</a></li>
		<li><a href='{{path('login')}}'>Iniciar sesión</a></li>
	</ul>
</div>

{% endif %}

templates/_includes/sharingbuttons.html.twig
{# Botones para las redes sociales #}
<section class="container">
	<!--Scripts necesarios para botones redes sociales-->
	<!--Twitter-->
	<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
	<!--facebook-->
	<div id="fb-root"></div>
	<script async defer crossorigin="anonymous"
	src="https://connect.facebook.net/es_ES/sdk.js#xfbml=1&version=v6.0"></script>


{# div para mostrar dichos botones #}
	<div class="row">

		<p class="text-muted col-12 col-md-5 offset-md-7 mb-0 p-0 font-weight-bold">COMPARTIR: <small class="text-right" id="clipboard"></small>

		</p>


		<div class="col-12 col-md-5 offset-md-7">
			<a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse" class="btn btn-facebook"><i class="fab fa-facebook"></i></a>

			<a target="_blank" href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="btn btn-twitter" data-size="large" data-text="Mira este sitio!" data-hashtags="Sevilla" data-show-count="false"><i class="fab fa-twitter"></i></a>

			<a class="btn btn-whatsapp" onclick="whatsApp();"><i class="fab fa-whatsapp"></i></a>

			<a class="btn btn-clipboard" onclick="clipboard();"><i class="fas fa-link"></i></a>

		</div>

	</div>

</section>